<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('referral_relationships', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->foreignUlid('referrer_id')->constrained('users')->cascadeOnDelete();
            $table->foreignUlid('referee_id')->constrained('users')->cascadeOnDelete();
            // 1 = direct referral, 2+ = generated by walking the referred_by chain,
            // capped at the referrer's affiliate tier's team_bonus_depth.
            $table->unsignedTinyInteger('level');
            $table->timestamp('created_at')->useCurrent();

            $table->unique(['referrer_id', 'referee_id', 'level'], 'referral_relationships_unique');
            $table->index('referee_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('referral_relationships');
    }
};
